import { createServer } from "./src/server.mjs";
import { loadConfig } from "./src/config.mjs";
const cfg = loadConfig();
cfg.onRailway = false;
cfg.port = 5224;
cfg.host = "127.0.0.1";
cfg.whatsappTransport = "linked-device";
cfg.adminEmail = "admin@local.com";
cfg.adminPassword = "LocalPass123!";
cfg.database = ":memory:";
cfg.mediaDir = "/tmp/wpp-local-media";
cfg.baileysAuthDir = "/tmp/wpp-baileys-auth";
const app = await createServer({ config: cfg });
app.domain.createCampaign({ code: "LOC", name: "Local Promo", startAt: "2026-09-01T00:00:00Z", endAt: "2026-11-30T00:00:00Z" });
const camp = app.domain.listCampaigns()[0];
app.domain.setCampaignStatus(camp.id, "active", "system");
app.domain.createVersion(camp.id, { content: {}, rules: { products: [{ sku: "ZSB-2KG", pack_weight_kg: 2 }], min_packs: 2, min_total_qty_kg: 4 }, flags: {} });
app.domain.upsertOutlet({ outlet_code: "OK-HRE-01", retailer: "OK Mart", branch: "Westgate", town: "Harare", province: "Harare" });
await app.listen();
console.log("LOCAL-READY");